//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POEStashSorter
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bike
    {
        public long Id { get; set; }
        public string BikeModel { get; set; }
        public Nullable<long> SprintSupport { get; set; }
        public Nullable<long> EnduranceSupport { get; set; }
        public Nullable<long> WheelGrip { get; set; }
        public Nullable<long> MaintanenceCost { get; set; }
        public Nullable<long> PurchaseCost { get; set; }
        public Nullable<long> Weight { get; set; }
    }
}
