//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("Model", "FK_Player_0_0", "Team", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(POEStashSorter.Team), "Player", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(POEStashSorter.Player), true)]
[assembly: EdmRelationshipAttribute("Model", "FK_Player_1_0", "Region", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(POEStashSorter.Region), "Player", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(POEStashSorter.Player), true)]
[assembly: EdmRelationshipAttribute("Model", "FK_Race_0_0", "Region", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(POEStashSorter.Region), "Race", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(POEStashSorter.Race), true)]
[assembly: EdmRelationshipAttribute("Model", "FK_TrackHill_0_0", "Race", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(POEStashSorter.Race), "TrackHill", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(POEStashSorter.TrackHill), true)]

#endregion

namespace POEStashSorter
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class Entities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new Entities object using the connection string found in the 'Entities' section of the application configuration file.
        /// </summary>
        public Entities() : base("name=Entities", "Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new Entities object.
        /// </summary>
        public Entities(string connectionString) : base(connectionString, "Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new Entities object.
        /// </summary>
        public Entities(EntityConnection connection) : base(connection, "Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Bike> Bike
        {
            get
            {
                if ((_Bike == null))
                {
                    _Bike = base.CreateObjectSet<Bike>("Bike");
                }
                return _Bike;
            }
        }
        private ObjectSet<Bike> _Bike;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Player> Player
        {
            get
            {
                if ((_Player == null))
                {
                    _Player = base.CreateObjectSet<Player>("Player");
                }
                return _Player;
            }
        }
        private ObjectSet<Player> _Player;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Race> Race
        {
            get
            {
                if ((_Race == null))
                {
                    _Race = base.CreateObjectSet<Race>("Race");
                }
                return _Race;
            }
        }
        private ObjectSet<Race> _Race;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Region> Region
        {
            get
            {
                if ((_Region == null))
                {
                    _Region = base.CreateObjectSet<Region>("Region");
                }
                return _Region;
            }
        }
        private ObjectSet<Region> _Region;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Team> Team
        {
            get
            {
                if ((_Team == null))
                {
                    _Team = base.CreateObjectSet<Team>("Team");
                }
                return _Team;
            }
        }
        private ObjectSet<Team> _Team;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<TrackHill> TrackHill
        {
            get
            {
                if ((_TrackHill == null))
                {
                    _TrackHill = base.CreateObjectSet<TrackHill>("TrackHill");
                }
                return _TrackHill;
            }
        }
        private ObjectSet<TrackHill> _TrackHill;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Bike EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToBike(Bike bike)
        {
            base.AddObject("Bike", bike);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Player EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPlayer(Player player)
        {
            base.AddObject("Player", player);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Race EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToRace(Race race)
        {
            base.AddObject("Race", race);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Region EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToRegion(Region region)
        {
            base.AddObject("Region", region);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Team EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTeam(Team team)
        {
            base.AddObject("Team", team);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the TrackHill EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTrackHill(TrackHill trackHill)
        {
            base.AddObject("TrackHill", trackHill);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model", Name="Bike")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Bike : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Bike object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        public static Bike CreateBike(global::System.Int64 id)
        {
            Bike bike = new Bike();
            bike.Id = id;
            return bike;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value, "Id");
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int64 _Id;
        partial void OnIdChanging(global::System.Int64 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String BikeModel
        {
            get
            {
                return _BikeModel;
            }
            set
            {
                OnBikeModelChanging(value);
                ReportPropertyChanging("BikeModel");
                _BikeModel = StructuralObject.SetValidValue(value, true, "BikeModel");
                ReportPropertyChanged("BikeModel");
                OnBikeModelChanged();
            }
        }
        private global::System.String _BikeModel;
        partial void OnBikeModelChanging(global::System.String value);
        partial void OnBikeModelChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> SprintSupport
        {
            get
            {
                return _SprintSupport;
            }
            set
            {
                OnSprintSupportChanging(value);
                ReportPropertyChanging("SprintSupport");
                _SprintSupport = StructuralObject.SetValidValue(value, "SprintSupport");
                ReportPropertyChanged("SprintSupport");
                OnSprintSupportChanged();
            }
        }
        private Nullable<global::System.Int64> _SprintSupport;
        partial void OnSprintSupportChanging(Nullable<global::System.Int64> value);
        partial void OnSprintSupportChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> EnduranceSupport
        {
            get
            {
                return _EnduranceSupport;
            }
            set
            {
                OnEnduranceSupportChanging(value);
                ReportPropertyChanging("EnduranceSupport");
                _EnduranceSupport = StructuralObject.SetValidValue(value, "EnduranceSupport");
                ReportPropertyChanged("EnduranceSupport");
                OnEnduranceSupportChanged();
            }
        }
        private Nullable<global::System.Int64> _EnduranceSupport;
        partial void OnEnduranceSupportChanging(Nullable<global::System.Int64> value);
        partial void OnEnduranceSupportChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> WheelGrip
        {
            get
            {
                return _WheelGrip;
            }
            set
            {
                OnWheelGripChanging(value);
                ReportPropertyChanging("WheelGrip");
                _WheelGrip = StructuralObject.SetValidValue(value, "WheelGrip");
                ReportPropertyChanged("WheelGrip");
                OnWheelGripChanged();
            }
        }
        private Nullable<global::System.Int64> _WheelGrip;
        partial void OnWheelGripChanging(Nullable<global::System.Int64> value);
        partial void OnWheelGripChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> MaintanenceCost
        {
            get
            {
                return _MaintanenceCost;
            }
            set
            {
                OnMaintanenceCostChanging(value);
                ReportPropertyChanging("MaintanenceCost");
                _MaintanenceCost = StructuralObject.SetValidValue(value, "MaintanenceCost");
                ReportPropertyChanged("MaintanenceCost");
                OnMaintanenceCostChanged();
            }
        }
        private Nullable<global::System.Int64> _MaintanenceCost;
        partial void OnMaintanenceCostChanging(Nullable<global::System.Int64> value);
        partial void OnMaintanenceCostChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> PurchaseCost
        {
            get
            {
                return _PurchaseCost;
            }
            set
            {
                OnPurchaseCostChanging(value);
                ReportPropertyChanging("PurchaseCost");
                _PurchaseCost = StructuralObject.SetValidValue(value, "PurchaseCost");
                ReportPropertyChanged("PurchaseCost");
                OnPurchaseCostChanged();
            }
        }
        private Nullable<global::System.Int64> _PurchaseCost;
        partial void OnPurchaseCostChanging(Nullable<global::System.Int64> value);
        partial void OnPurchaseCostChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> Weight
        {
            get
            {
                return _Weight;
            }
            set
            {
                OnWeightChanging(value);
                ReportPropertyChanging("Weight");
                _Weight = StructuralObject.SetValidValue(value, "Weight");
                ReportPropertyChanged("Weight");
                OnWeightChanged();
            }
        }
        private Nullable<global::System.Int64> _Weight;
        partial void OnWeightChanging(Nullable<global::System.Int64> value);
        partial void OnWeightChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model", Name="Player")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Player : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Player object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        public static Player CreatePlayer(global::System.Int64 id)
        {
            Player player = new Player();
            player.Id = id;
            return player;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value, "Id");
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int64 _Id;
        partial void OnIdChanging(global::System.Int64 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> Credits
        {
            get
            {
                return _Credits;
            }
            set
            {
                OnCreditsChanging(value);
                ReportPropertyChanging("Credits");
                _Credits = StructuralObject.SetValidValue(value, "Credits");
                ReportPropertyChanged("Credits");
                OnCreditsChanged();
            }
        }
        private Nullable<global::System.Int64> _Credits;
        partial void OnCreditsChanging(Nullable<global::System.Int64> value);
        partial void OnCreditsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> RegionId
        {
            get
            {
                return _RegionId;
            }
            set
            {
                OnRegionIdChanging(value);
                ReportPropertyChanging("RegionId");
                _RegionId = StructuralObject.SetValidValue(value, "RegionId");
                ReportPropertyChanged("RegionId");
                OnRegionIdChanged();
            }
        }
        private Nullable<global::System.Int64> _RegionId;
        partial void OnRegionIdChanging(Nullable<global::System.Int64> value);
        partial void OnRegionIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> TeamId
        {
            get
            {
                return _TeamId;
            }
            set
            {
                OnTeamIdChanging(value);
                ReportPropertyChanging("TeamId");
                _TeamId = StructuralObject.SetValidValue(value, "TeamId");
                ReportPropertyChanged("TeamId");
                OnTeamIdChanged();
            }
        }
        private Nullable<global::System.Int64> _TeamId;
        partial void OnTeamIdChanging(Nullable<global::System.Int64> value);
        partial void OnTeamIdChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model", "FK_Player_0_0", "Team")]
        public Team Team
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Team>("Model.FK_Player_0_0", "Team").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Team>("Model.FK_Player_0_0", "Team").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Team> TeamReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Team>("Model.FK_Player_0_0", "Team");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Team>("Model.FK_Player_0_0", "Team", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model", "FK_Player_1_0", "Region")]
        public Region Region
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Region>("Model.FK_Player_1_0", "Region").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Region>("Model.FK_Player_1_0", "Region").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Region> RegionReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Region>("Model.FK_Player_1_0", "Region");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Region>("Model.FK_Player_1_0", "Region", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model", Name="Race")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Race : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Race object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        public static Race CreateRace(global::System.Int64 id)
        {
            Race race = new Race();
            race.Id = id;
            return race;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value, "Id");
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int64 _Id;
        partial void OnIdChanging(global::System.Int64 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> RegionId
        {
            get
            {
                return _RegionId;
            }
            set
            {
                OnRegionIdChanging(value);
                ReportPropertyChanging("RegionId");
                _RegionId = StructuralObject.SetValidValue(value, "RegionId");
                ReportPropertyChanged("RegionId");
                OnRegionIdChanged();
            }
        }
        private Nullable<global::System.Int64> _RegionId;
        partial void OnRegionIdChanging(Nullable<global::System.Int64> value);
        partial void OnRegionIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> PrizePool
        {
            get
            {
                return _PrizePool;
            }
            set
            {
                OnPrizePoolChanging(value);
                ReportPropertyChanging("PrizePool");
                _PrizePool = StructuralObject.SetValidValue(value, "PrizePool");
                ReportPropertyChanged("PrizePool");
                OnPrizePoolChanged();
            }
        }
        private Nullable<global::System.Int64> _PrizePool;
        partial void OnPrizePoolChanging(Nullable<global::System.Int64> value);
        partial void OnPrizePoolChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CityName
        {
            get
            {
                return _CityName;
            }
            set
            {
                OnCityNameChanging(value);
                ReportPropertyChanging("CityName");
                _CityName = StructuralObject.SetValidValue(value, true, "CityName");
                ReportPropertyChanged("CityName");
                OnCityNameChanged();
            }
        }
        private global::System.String _CityName;
        partial void OnCityNameChanging(global::System.String value);
        partial void OnCityNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> IsAvailable
        {
            get
            {
                return _IsAvailable;
            }
            set
            {
                OnIsAvailableChanging(value);
                ReportPropertyChanging("IsAvailable");
                _IsAvailable = StructuralObject.SetValidValue(value, "IsAvailable");
                ReportPropertyChanged("IsAvailable");
                OnIsAvailableChanged();
            }
        }
        private Nullable<global::System.Int64> _IsAvailable;
        partial void OnIsAvailableChanging(Nullable<global::System.Int64> value);
        partial void OnIsAvailableChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model", "FK_Race_0_0", "Region")]
        public Region Region
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Region>("Model.FK_Race_0_0", "Region").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Region>("Model.FK_Race_0_0", "Region").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Region> RegionReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Region>("Model.FK_Race_0_0", "Region");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Region>("Model.FK_Race_0_0", "Region", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model", "FK_TrackHill_0_0", "TrackHill")]
        public EntityCollection<TrackHill> TrackHill
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<TrackHill>("Model.FK_TrackHill_0_0", "TrackHill");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<TrackHill>("Model.FK_TrackHill_0_0", "TrackHill", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model", Name="Region")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Region : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Region object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        public static Region CreateRegion(global::System.Int64 id)
        {
            Region region = new Region();
            region.Id = id;
            return region;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value, "Id");
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int64 _Id;
        partial void OnIdChanging(global::System.Int64 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String RegionName
        {
            get
            {
                return _RegionName;
            }
            set
            {
                OnRegionNameChanging(value);
                ReportPropertyChanging("RegionName");
                _RegionName = StructuralObject.SetValidValue(value, true, "RegionName");
                ReportPropertyChanged("RegionName");
                OnRegionNameChanged();
            }
        }
        private global::System.String _RegionName;
        partial void OnRegionNameChanging(global::System.String value);
        partial void OnRegionNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TerrainType
        {
            get
            {
                return _TerrainType;
            }
            set
            {
                OnTerrainTypeChanging(value);
                ReportPropertyChanging("TerrainType");
                _TerrainType = StructuralObject.SetValidValue(value, true, "TerrainType");
                ReportPropertyChanged("TerrainType");
                OnTerrainTypeChanged();
            }
        }
        private global::System.String _TerrainType;
        partial void OnTerrainTypeChanging(global::System.String value);
        partial void OnTerrainTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SkillLevel
        {
            get
            {
                return _SkillLevel;
            }
            set
            {
                OnSkillLevelChanging(value);
                ReportPropertyChanging("SkillLevel");
                _SkillLevel = StructuralObject.SetValidValue(value, true, "SkillLevel");
                ReportPropertyChanged("SkillLevel");
                OnSkillLevelChanged();
            }
        }
        private global::System.String _SkillLevel;
        partial void OnSkillLevelChanging(global::System.String value);
        partial void OnSkillLevelChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model", "FK_Player_1_0", "Player")]
        public EntityCollection<Player> Player
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Player>("Model.FK_Player_1_0", "Player");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Player>("Model.FK_Player_1_0", "Player", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model", "FK_Race_0_0", "Race")]
        public EntityCollection<Race> Race
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Race>("Model.FK_Race_0_0", "Race");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Race>("Model.FK_Race_0_0", "Race", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model", Name="Team")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Team : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Team object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        public static Team CreateTeam(global::System.Int64 id)
        {
            Team team = new Team();
            team.Id = id;
            return team;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value, "Id");
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int64 _Id;
        partial void OnIdChanging(global::System.Int64 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> OverallEndurance
        {
            get
            {
                return _OverallEndurance;
            }
            set
            {
                OnOverallEnduranceChanging(value);
                ReportPropertyChanging("OverallEndurance");
                _OverallEndurance = StructuralObject.SetValidValue(value, "OverallEndurance");
                ReportPropertyChanged("OverallEndurance");
                OnOverallEnduranceChanged();
            }
        }
        private Nullable<global::System.Double> _OverallEndurance;
        partial void OnOverallEnduranceChanging(Nullable<global::System.Double> value);
        partial void OnOverallEnduranceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> OverallSprint
        {
            get
            {
                return _OverallSprint;
            }
            set
            {
                OnOverallSprintChanging(value);
                ReportPropertyChanging("OverallSprint");
                _OverallSprint = StructuralObject.SetValidValue(value, "OverallSprint");
                ReportPropertyChanged("OverallSprint");
                OnOverallSprintChanged();
            }
        }
        private Nullable<global::System.Double> _OverallSprint;
        partial void OnOverallSprintChanging(Nullable<global::System.Double> value);
        partial void OnOverallSprintChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> TeamRating
        {
            get
            {
                return _TeamRating;
            }
            set
            {
                OnTeamRatingChanging(value);
                ReportPropertyChanging("TeamRating");
                _TeamRating = StructuralObject.SetValidValue(value, "TeamRating");
                ReportPropertyChanged("TeamRating");
                OnTeamRatingChanged();
            }
        }
        private Nullable<global::System.Int64> _TeamRating;
        partial void OnTeamRatingChanging(Nullable<global::System.Int64> value);
        partial void OnTeamRatingChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model", "FK_Player_0_0", "Player")]
        public EntityCollection<Player> Player
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Player>("Model.FK_Player_0_0", "Player");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Player>("Model.FK_Player_0_0", "Player", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model", Name="TrackHill")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TrackHill : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new TrackHill object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        public static TrackHill CreateTrackHill(global::System.Int64 id)
        {
            TrackHill trackHill = new TrackHill();
            trackHill.Id = id;
            return trackHill;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value, "Id");
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int64 _Id;
        partial void OnIdChanging(global::System.Int64 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> Length
        {
            get
            {
                return _Length;
            }
            set
            {
                OnLengthChanging(value);
                ReportPropertyChanging("Length");
                _Length = StructuralObject.SetValidValue(value, "Length");
                ReportPropertyChanged("Length");
                OnLengthChanged();
            }
        }
        private Nullable<global::System.Int64> _Length;
        partial void OnLengthChanging(Nullable<global::System.Int64> value);
        partial void OnLengthChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> Slope
        {
            get
            {
                return _Slope;
            }
            set
            {
                OnSlopeChanging(value);
                ReportPropertyChanging("Slope");
                _Slope = StructuralObject.SetValidValue(value, "Slope");
                ReportPropertyChanged("Slope");
                OnSlopeChanged();
            }
        }
        private Nullable<global::System.Int64> _Slope;
        partial void OnSlopeChanging(Nullable<global::System.Int64> value);
        partial void OnSlopeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> RaceId
        {
            get
            {
                return _RaceId;
            }
            set
            {
                OnRaceIdChanging(value);
                ReportPropertyChanging("RaceId");
                _RaceId = StructuralObject.SetValidValue(value, "RaceId");
                ReportPropertyChanged("RaceId");
                OnRaceIdChanged();
            }
        }
        private Nullable<global::System.Int64> _RaceId;
        partial void OnRaceIdChanging(Nullable<global::System.Int64> value);
        partial void OnRaceIdChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model", "FK_TrackHill_0_0", "Race")]
        public Race Race
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Race>("Model.FK_TrackHill_0_0", "Race").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Race>("Model.FK_TrackHill_0_0", "Race").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Race> RaceReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Race>("Model.FK_TrackHill_0_0", "Race");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Race>("Model.FK_TrackHill_0_0", "Race", value);
                }
            }
        }

        #endregion

    }

    #endregion

}
