//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POEStashSorter
{
    using System;
    using System.Collections.Generic;
    
    public partial class Region
    {
        public Region()
        {
            this.Player = new HashSet<Player>();
            this.Race = new HashSet<Race>();
        }
    
        public long Id { get; set; }
        public string RegionName { get; set; }
        public string TerrainType { get; set; }
        public string SkillLevel { get; set; }
    
        public virtual ICollection<Player> Player { get; set; }
        public virtual ICollection<Race> Race { get; set; }
    }
}
