//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POEStashSorter
{
    using System;
    using System.Collections.Generic;
    
    public partial class Team
    {
        public Team()
        {
            this.Player = new HashSet<Player>();
        }
    
        public long Id { get; set; }
        public Nullable<double> OverallEndurance { get; set; }
        public Nullable<double> OverallSprint { get; set; }
        public Nullable<long> TeamRating { get; set; }
    
        public virtual ICollection<Player> Player { get; set; }
    }
}
