//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POEStashSorter
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrackHill
    {
        public long Id { get; set; }
        public Nullable<long> Length { get; set; }
        public Nullable<long> Slope { get; set; }
        public Nullable<long> RaceId { get; set; }
    
        public virtual Race Race { get; set; }
    }
}
